# ============================================================
# modules/logging/main.tf — Cloud Logging export sink
# ============================================================
# Cloud Logging retains logs for 30 days by default (free tier).
# This module creates a *log sink* — a rule that continuously
# exports a filtered stream of logs to a GCS bucket.
#
# Use cases:
#   • Long-term audit log retention (compliance)
#   • Batch analysis with BigQuery (point the sink there instead)
#   • Cost reduction (GCS is cheaper than extended Logging retention)
#
# How a sink works:
#   1. Cloud Logging matches each incoming log entry against the filter.
#   2. Matched entries are forwarded to the destination (GCS bucket here).
#   3. A dedicated sink service account writes the objects — you must grant
#      it objectCreator on the destination bucket (done below).

resource "google_logging_project_sink" "gcs_sink" {
  name    = var.sink_name
  project = var.project_id

  # destination format for GCS: "storage.googleapis.com/<bucket-name>"
  # Other options: bigquery.googleapis.com/projects/.../datasets/... or
  #                pubsub.googleapis.com/projects/.../topics/...
  destination = "storage.googleapis.com/${var.log_bucket_name}"

  # filter uses the same syntax as the Cloud Logging query builder.
  # Empty string ("") exports ALL logs — use with caution on high-traffic projects.
  # Example to export only GKE container logs:
  #   resource.type="k8s_container"
  filter = var.log_filter

  # unique_writer_identity = true instructs GCP to create a dedicated SA
  # for this sink (e.g. serviceAccount:p12345-abc@gcp-sa-logging.iam.gserviceaccount.com).
  # Using a unique identity is safer than the shared logging SA.
  unique_writer_identity = true
}

# Grant the sink's SA permission to create objects in the log bucket.
# The sink writes log batches as Avro/JSON files; without this binding
# the sink is created but silently drops every exported entry.
resource "google_storage_bucket_iam_member" "log_sink_writer" {
  bucket = var.log_bucket_name
  role   = "roles/storage.objectCreator"

  # writer_identity is the SA email generated by the sink resource above.
  member = google_logging_project_sink.gcs_sink.writer_identity
}
